[package]
name = "cafe_manager_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"
jsonwebtoken = "9.3.0"
swagger-ui = "0.1"